default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmanager_d

test:
  <<: *default
  database: taskmanager_test

production:
  <<: *default
  database: taskmanager
  username: taskManager
  password: <%= ENV['TASKMANAGER_DATABASE_PASSWORD'] %>
